/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsAdvisory {
  ruleId: string
  severity: string
  observation: string
  impact: string
  improvement: string
  line: number
  column: number
  filePath: string
}
export declare class GenSenseEngine {
  constructor()
  enableTag(tag: string): void
  setEnvironment(env: string): void
  auditContent(filePath: string, content: string): Array<JsAdvisory>
  auditPath(path: string): Array<JsAdvisory>
}
