// [frensense]
// observation: A file path generated by an LLM is passed directly to filesystem operations like readFile or writeFile.
// impact: An attacker who influences LLM output can read arbitrary server files or write malicious content to the filesystem.
// improvement: Restrict file operations to a specific sandboxed directory and validate that the resolved path stays within it.

import OpenAI from 'openai';
import fs from 'fs/promises';

const openai = new OpenAI();

export async function readFileSuggestion(prompt: string) {
  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [{ role: 'user', content: `What file should I read to understand ${prompt}?` }]
  });
  const filePath = response.choices[0].message.content;
  const content = await fs.readFile(filePath, 'utf-8');
  return content;
}
