// [frensense]
// observation: A URL generated by an LLM is fetched directly using fetch(), enabling SSRF via the model.
// impact: An attacker who controls the LLM's training data or prompt can make the server request internal services or fetch malicious payloads.
// improvement: Validate LLM-generated URLs against an allowlist of permitted domains before making the request.

import OpenAI from 'openai';

const openai = new OpenAI();

export async function fetchFromModel(url: string) {
  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [{ role: 'user', content: `Find the API endpoint for user data at: ${url}` }]
  });
  const modelUrl = response.choices[0].message.content;
  const data = await fetch(modelUrl);
  return data.json();
}
