// Vulnerable: 'reflect.MakeFunc' detected. This will sidestep protections that are normally afforded by Go's type system. Audit this call and be sure that user input cannot be used to affect the code generated by MakeFunc; otherwise, you will have a serious security vulnerability.
// Pattern: reflect.MakeFunc(...)
function vulnerable() {
  // TODO: implement pattern match
}
