// [LICENSE] Proprietary - Friehub (TaaS Gateway)
// Copyright (c) 2026 Friehub. All rights reserved.

use crate::Advisory;
use std::path::Path;

pub struct Reporter;

impl Reporter {
    /// Generates a professional Markdown report grouped by severity.
    pub fn to_markdown(advisories: &[Advisory], path: &str) -> String {
        let mut md = format!("# GenSense: Semantic Analysis Report for {path}\n\n");
        md.push_str("> [!IMPORTANT]\n> This report contains automated structural observations. High-severity items should be prioritized for protocol stability.\n\n");

        if advisories.is_empty() {
            md.push_str("**Analysis Complete:** No structural concerns identified. The code adheres to standardized standards!\n");
            return md;
        }

        let severities = [
            crate::Severity::Critical,
            crate::Severity::Warning,
            crate::Severity::Info,
        ];
        for sev in severities {
            let filtered: Vec<&Advisory> =
                advisories.iter().filter(|a| a.severity == sev).collect();
            if filtered.is_empty() {
                continue;
            }

            let title = match sev {
                crate::Severity::Critical => "## Critical Security & Reliability Risks",
                crate::Severity::Warning => "## Technical Debt & Quality Warnings",
                crate::Severity::Info => "## Standardized & Style Suggestions",
            };
            md.push_str(&format!("{title}\n\n"));

            for adv in filtered {
                md.push_str(&format!("### {}\n", adv.rule_id));
                md.push_str(&format!("- **Location**: `line {}`  \n", adv.line));
                md.push_str(&format!("- **Observation**: {}  \n", adv.observation));
                md.push_str(&format!("- **Impact**: {}  \n", adv.impact));
                md.push_str(&format!("- **Improvement**: {}  \n\n", adv.improvement));
            }
        }

        md.push_str("---\n*Generated by GenSense - Semantic Insight Engine*\n");
        md
    }

    /// Generates a SARIF (Static Analysis Results Interchange Format) report for CI/CD integration.
    pub fn to_sarif(advisories: &[Advisory], _root_path: &Path) -> serde_json::Value {
        let runs = serde_json::json!([{
            "tool": {
                "driver": {
                    "name": "GenSense",
                    "version": "1.0.0",
                    "informationUri": "https://friehub.com/taas"
                }
            },
            "results": advisories.iter().map(|adv| {
                serde_json::json!({
                    "ruleId": adv.rule_id,
                    "level": match adv.severity {
                        crate::Severity::Critical => "error",
                        crate::Severity::Warning => "warning",
                        crate::Severity::Info => "note",
                    },
                    "message": {
                        "text": format!("{}\n\nImpact: {}\n\nImprovement: {}", adv.observation, adv.impact, adv.improvement)
                    },
                    "locations": [{
                        "physicalLocation": {
                            "artifactLocation": {
                                "uri": adv.file_path.clone()
                            },
                            "region": {
                                "startLine": adv.line,
                                "startColumn": adv.column
                            }
                        }
                    }]
                })
            }).collect::<Vec<_>>()
        }]);

        serde_json::json!({
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": runs
        })
    }
}
