// SPDX-License-Identifier: MIT

use crate::Advisory;
use std::fmt::Write;
use std::path::Path;

pub struct Reporter;

impl Reporter {
    /// Generates a professional Markdown report grouped by severity.
    #[must_use]
    pub fn to_markdown(advisories: &[Advisory], path: &str) -> String {
        let mut md = format!("# GenSense: Semantic Analysis Report for {path}\n\n");
        md.push_str("> [!IMPORTANT]\n> This report contains automated structural observations. High-severity items should be prioritized for protocol stability.\n\n");

        if advisories.is_empty() {
            md.push_str("**Analysis Complete:** No structural concerns identified. The code adheres to standardized standards!\n");
            return md;
        }

        let severities = [
            crate::Severity::Critical,
            crate::Severity::Warning,
            crate::Severity::Info,
        ];
        for sev in severities {
            let filtered: Vec<&Advisory> =
                advisories.iter().filter(|a| a.severity == sev).collect();
            if filtered.is_empty() {
                continue;
            }

            let title = match sev {
                crate::Severity::Critical => "## Critical Security & Reliability Risks",
                crate::Severity::Warning => "## Technical Debt & Quality Warnings",
                crate::Severity::Info => "## Standardized & Style Suggestions",
            };
            let _ = writeln!(md, "{title}\n");

            for adv in filtered {
                let _ = writeln!(md, "### {}", adv.rule_id);
                let _ = writeln!(md, "- **Location**: `line {}`  ", adv.line);
                let _ = writeln!(md, "- **Observation**: {}  ", adv.observation);
                let _ = writeln!(md, "- **Impact**: {}  ", adv.impact);
                let _ = writeln!(md, "- **Improvement**: {}  \n", adv.improvement);
            }
        }

        md.push_str("---\n*Generated by GenSense - Semantic Insight Engine*\n");
        md
    }

    /// Generates a SARIF (Static Analysis Results Interchange Format) report for CI/CD integration.
    #[must_use]
    pub fn to_sarif(advisories: &[Advisory], _root_path: &Path) -> serde_json::Value {
        let mut rules_map = std::collections::BTreeMap::new();
        for adv in advisories {
            if !rules_map.contains_key(&adv.rule_id) {
                rules_map.insert(
                    adv.rule_id.clone(),
                    serde_json::json!({
                        "id": adv.rule_id,
                        "shortDescription": {
                            "text": adv.observation.clone()
                        },
                        "fullDescription": {
                            "text": format!("{}\n\nImpact: {}\n\nImprovement: {}", adv.observation, adv.impact, adv.improvement)
                        },
                        "helpUri": format!("https://friehub.github.io/gensense/rules/{}", adv.rule_id)
                    }),
                );
            }
        }
        let rules_list: Vec<_> = rules_map.into_values().collect();

        let runs = serde_json::json!([{
            "tool": {
                "driver": {
                    "name": "GenSense",
                    "version": crate::GENSENSE_VERSION,
                    "informationUri": "https://friehub.com/gensense",
                    "rules": rules_list
                }
            },
            "results": advisories.iter().map(|adv| {
                let line_count = adv.original_content.lines().count();
                let end_line = adv.line + u32::try_from(line_count.saturating_sub(1)).unwrap_or(0);
                let end_column = if line_count > 1 {
                    u32::try_from(adv.original_content.lines().last().map(|l| l.len()).unwrap_or(0) + 1).unwrap_or(1)
                } else {
                    adv.column + u32::try_from(adv.original_content.len()).unwrap_or(0)
                };

                let mut result = serde_json::json!({
                    "ruleId": adv.rule_id,
                    "level": match adv.severity {
                        crate::Severity::Critical => "error",
                        crate::Severity::Warning => "warning",
                        crate::Severity::Info => "note",
                    },
                    "message": {
                        "text": format!("{}\n\nImpact: {}\n\nImprovement: {}", adv.observation, adv.impact, adv.improvement)
                    },
                    "locations": [{
                        "physicalLocation": {
                            "artifactLocation": {
                                "uri": adv.file_path.clone()
                            },
                            "region": {
                                "startLine": adv.line,
                                "startColumn": adv.column,
                                "endLine": end_line,
                                "endColumn": end_column
                            }
                        }
                    }],
                    "partialFingerprints": {
                        "primaryLocationLineHash/v1": adv.fingerprint
                    },
                    "properties": {
                        "confidence": adv.confidence,
                        "auto_fixable": adv.auto_fixable,
                        "requires_human": adv.requires_human,
                        "tags": adv.tags
                    }
                });

                if let Some(replacement) = &adv.proposed_replacement {
                    result["fixes"] = serde_json::json!([{
                        "description": {
                            "text": "Apply suggested auto-remediation fix"
                        },
                        "artifactChanges": [{
                            "artifactLocation": {
                                "uri": adv.file_path.clone()
                            },
                            "replacements": [{
                                "deletedRegion": {
                                    "byteOffset": adv.start_byte,
                                    "byteLength": adv.end_byte.saturating_sub(adv.start_byte)
                                },
                                "insertedContent": {
                                    "text": replacement.clone()
                                }
                            }]
                        }]
                    }]);
                }

                result
            }).collect::<Vec<_>>()
        }]);

        serde_json::json!({
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": runs
        })
    }
}
