// [frensense]
// observation: Invoice line items are generated by re-querying the order, not by using the actual fulfilled/shipped items, creating a mismatch when order is modified after fulfillment.
// impact: Customers are charged for items they didn't receive or not charged for items they did, causing revenue leakage and billing disputes.
// improvement: Generate invoice line items from the fulfillment/shipment records, not from the current order state.
// cwe: CWE-754
// cvss: 6.5
// owasp: A04:2021
// severity: Medium

import { PrismaClient } from '@prisma/client';
import { Request, Response } from 'express';

const prisma = new PrismaClient();

export async function generateInvoice(req: Request, res: Response) {
  const { orderId } = req.params;

  const order = await prisma.order.findUnique({
    where: { id: orderId },
    include: { items: true },
  });

  const total = order.items.reduce((sum, item) => sum + item.price * item.quantity, 0);

  const invoice = await prisma.invoice.create({
    data: {
      orderId: order.id,
      total,
      lineItems: {
        create: order.items.map((item) => ({
          productId: item.productId,
          quantity: item.quantity,
          unitPrice: item.price,
          total: item.price * item.quantity,
        })),
      },
    },
  });

  res.json(invoice);
}
